---
- hosts: all
  become_user: root

  vars:
    ntp_server1:  ntp.t-2.net

  tasks:
    - name: check/install ntp client package
      apt:
        name=ntp
        state=present
   
    - name: deploy ntp.conf to hosts
      template:
        src=/home/nives/ansible_tutorial/templates/ntp.j2
        dest=/etc/ntp.conf
        owner=root
        group=root
        mode=0644
        backup=yes

    - name: ensure ntpd is running and enabled
      service:
        name=ntpd
        state=restarted
        enabled=yes

